version: "3.8"

services:
  db:
    image: mysql
    restart: always
    env_file: .env
    environment:
      - MYSQL_DATABASE=$MYSQL_DATABASE
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
    container_name: db
    ports:
      - "3307:3306"
    volumes:
      - db-config:/etc/mysql
      - db-data:/var/lib/mysql
      - ./db/backup/files/:/data_backup/data
    expose:
      - "3307"
    networks:
      - backend

  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file: .env
    environment:
      - MYSQL_HOST=db
    volumes:
      - ./app:/app
      - ./app/node_modules
    depends_on:
      - db
    networks:
      - backend
    links:
      - db
    ports:
      - "2000:2000"
    restart: always
    container_name: api-node

networks:
  backend:
volumes:
  db-config:
  db-data:
