apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql
          env:
            - name: MYSQL_DATABASE
              value: "Users"
            - name: MYSQL_ROOT_PASSWORD
              value: "157892"
            - name: MYSQL_HOST
              value: 172.17.0.2
          ports:
            - containerPort: 3306
