kind: Service
apiVersion: v1
metadata:
  name: mysql
spec:
  selector:
    app: api-mysql
  ports:
    - protocol: TCP
      port: 3306
  type: LoadBalancer
  externalIPs:
    - 192.168.49.2
    
---
kind: Service
apiVersion: v1
metadata:
  name: api-service
spec:
  selector:
    app: api-node
  ports:
    - protocol: TCP
      port: 2000
      targetPort: 2000
  type: LoadBalancer
  externalIPs:
    - 192.168.49.2

