

name: Build and Push Docker Image

on:

  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

 
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    -
      name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: dancairo
        password: 19091993
    -
      name: Build and Push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        dockerfile: .
        push: true
        tags: dancairo/api-nodejs:v1
        
    -
      name: Image api nodejs
      run: echo ${{ steps.docker_build.outputs.digest }}
    
 
